import type { MetadataRoute } from "next";

/**
 * PWA Manifest — generated by Next.js at /manifest.webmanifest
 *
 * This powers "Add to Home Screen" on both Android (Chrome) and iOS (Safari).
 * - Android: triggers the native install prompt when criteria are met
 *   (HTTPS, valid manifest, registered service worker)
 * - iOS: Safari shows "Add to Home Screen" in the share menu; the manifest
 *   provides the icon, name, and theme color
 *
 * Maskable icons are critical for Android adaptive icon support.
 */
export default function manifest(): MetadataRoute.Manifest {
  return {
    name: "Veda Enterprises ERP",
    short_name: "Veda ERP",
    description:
      "ERP & Management System for Veda Enterprises. Manage production, stock, dispatch, payments, and reports from one platform.",
    start_url: "/",
    scope: "/",
    display: "standalone",
    orientation: "any",
    background_color: "#ffffff",
    theme_color: "#059669",
    categories: ["business", "productivity", "finance"],
    lang: "en",
    dir: "ltr",
    icons: [
      {
        src: "/icons/icon-192x192.png",
        sizes: "192x192",
        type: "image/png",
        purpose: "any",
      },
      {
        src: "/icons/icon-256x256.png",
        sizes: "256x256",
        type: "image/png",
        purpose: "any",
      },
      {
        src: "/icons/icon-384x384.png",
        sizes: "384x384",
        type: "image/png",
        purpose: "any",
      },
      {
        src: "/icons/icon-512x512.png",
        sizes: "512x512",
        type: "image/png",
        purpose: "any",
      },
      // Maskable: Android adaptive icon support — required for proper
      // integration with Android's home screen icon shapes
      {
        src: "/icons/icon-maskable-512x512.png",
        sizes: "512x512",
        type: "image/png",
        purpose: "maskable",
      },
      {
        src: "/icons/icon-192x192.png",
        sizes: "192x192",
        type: "image/png",
        purpose: "maskable",
      },
    ],
    shortcuts: [
      {
        name: "Dashboard",
        short_name: "Home",
        description: "Open the main ERP dashboard",
        url: "/?view=dashboard",
      },
      {
        name: "Production",
        short_name: "Production",
        description: "View production orders",
        url: "/?view=production",
      },
      {
        name: "Stock",
        short_name: "Stock",
        description: "View stock inventory",
        url: "/?view=stock",
      },
    ],
  };
}
